"""
banco.py — Conexão e CRUD com Oracle (Cap. 6)

Este módulo encapsula tudo o que toca o banco Oracle da FIAP:
  * Abertura de conexão (modo "thin", sem precisar de Oracle Instant Client).
  * Criação da tabela 'talhoes' se ainda não existir.
  * CRUD completo: inserir, listar, atualizar, excluir.
  * Sincronização bidirecional: memória -> Oracle e Oracle -> memória.

Credenciais são carregadas de variáveis de ambiente (arquivo .env).
"""

import os

# oracledb: driver oficial da Oracle para Python (substitui o antigo cx_Oracle).
import oracledb
from dotenv import load_dotenv

# Reimportamos recalcular_talhao para aproveitar a lógica de perdas/classificação
# ao reconstruir dicionários a partir dos registros do banco.
from funcoes import recalcular_talhao


# Carrega variáveis do .env para o ambiente (no-op se o arquivo não existir).
load_dotenv()


# ---------------------------------------------------------------------------
# CREDENCIAIS (carregadas do .env)
# ---------------------------------------------------------------------------
CREDENCIAIS = {
    "host": os.getenv("DB_HOST"),
    "porta": int(os.getenv("DB_PORT", "1521")),
    "service_name": os.getenv("DB_SERVICE_NAME"),
    "usuario": os.getenv("DB_USER"),
    "senha": os.getenv("DB_PASSWORD"),
}


# ---------------------------------------------------------------------------
# CONEXÃO
# ---------------------------------------------------------------------------
def conectar():
    """Abre e devolve uma conexão com o Oracle. Lança exceção em caso de falha."""
    # makedsn monta a string DSN a partir dos componentes (host, porta, service).
    dsn = oracledb.makedsn(
        CREDENCIAIS["host"],
        CREDENCIAIS["porta"],
        service_name=CREDENCIAIS["service_name"],
    )
    # connect abre a conexão; modo 'thin' é o padrão e dispensa Instant Client.
    conn = oracledb.connect(
        user=CREDENCIAIS["usuario"],
        password=CREDENCIAIS["senha"],
        dsn=dsn,
    )
    # Devolve a conexão para o chamador usar.
    return conn


# ---------------------------------------------------------------------------
# CRIAÇÃO DA TABELA (idempotente)
# ---------------------------------------------------------------------------
# String SQL de criação. Usa IDENTITY para PK auto-incremental.
_SQL_CRIAR_TABELA = """
CREATE TABLE talhoes (
    id                   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome                 VARCHAR2(100) NOT NULL,
    area_ha              NUMBER(10,2)  NOT NULL,
    tipo_colheita        VARCHAR2(10)  NOT NULL,
    producao_esperada_t  NUMBER(10,2)  NOT NULL,
    producao_colhida_t   NUMBER(10,2)  NOT NULL,
    safra                VARCHAR2(20)
)
"""


def garantir_tabela(conn):
    """Cria a tabela 'talhoes' se ainda não existir. Idempotente."""
    # Cursor é o objeto usado para executar comandos SQL.
    cursor = conn.cursor()
    try:
        # Tenta executar o CREATE TABLE.
        cursor.execute(_SQL_CRIAR_TABELA)
        # Confirma a criação (DDL em Oracle já dá commit implícito, mas garantimos).
        conn.commit()
        print("  [OK] Tabela 'talhoes' criada.")
    except oracledb.DatabaseError as erro:
        # Extrai o objeto de erro Oracle para inspecionar o código.
        (obj_erro,) = erro.args
        # ORA-00955: "nome já está sendo usado por um objeto existente".
        # Nesse caso a tabela já existe -> comportamento esperado, não é erro.
        if obj_erro.code == 955:
            pass  # Tabela já existe; seguimos em frente.
        else:
            # Outro erro -> repropaga para o chamador tratar.
            raise
    finally:
        # Sempre fecha o cursor, mesmo se houve erro.
        cursor.close()


# ---------------------------------------------------------------------------
# INSERIR
# ---------------------------------------------------------------------------
def inserir_talhao(conn, talhao):
    """Insere um talhão no Oracle e devolve o id gerado pela coluna IDENTITY."""
    # Cria o cursor.
    cursor = conn.cursor()
    # Cria uma variável de bind para capturar o id gerado pelo INSERT.
    id_var = cursor.var(oracledb.NUMBER)

    # SQL com placeholders nomeados + RETURNING para obter o id gerado.
    sql = """
        INSERT INTO talhoes
            (nome, area_ha, tipo_colheita,
             producao_esperada_t, producao_colhida_t, safra)
        VALUES
            (:nome, :area_ha, :tipo_colheita,
             :producao_esperada_t, :producao_colhida_t, :safra)
        RETURNING id INTO :id_gerado
    """
    # Executa passando um dicionário de binds para evitar SQL injection.
    cursor.execute(sql, {
        "nome": talhao["nome"],
        "area_ha": talhao["area_ha"],
        "tipo_colheita": talhao["tipo_colheita"],
        "producao_esperada_t": talhao["producao_esperada_t"],
        "producao_colhida_t": talhao["producao_colhida_t"],
        "safra": talhao["safra"],
        "id_gerado": id_var,
    })
    # Recupera o id gerado (getvalue devolve lista; pegamos o primeiro).
    id_gerado = int(id_var.getvalue()[0])
    # Confirma a transação.
    conn.commit()
    # Fecha o cursor.
    cursor.close()
    # Devolve o id para o chamador guardar no dicionário em memória.
    return id_gerado


# ---------------------------------------------------------------------------
# LISTAR
# ---------------------------------------------------------------------------
def listar_talhoes(conn):
    """Lê todos os talhões do banco e devolve uma lista de dicts já recalculados."""
    cursor = conn.cursor()
    # SELECT com ordenação por id para mostrar em ordem cronológica.
    cursor.execute("""
        SELECT id, nome, area_ha, tipo_colheita,
               producao_esperada_t, producao_colhida_t, safra
          FROM talhoes
         ORDER BY id
    """)
    # Lista onde vamos acumular os dicts reconstruídos.
    resultado = []
    # fetchall devolve todas as linhas de uma vez.
    for linha in cursor.fetchall():
        # Desempacota a linha em variáveis nomeadas para legibilidade.
        (id_db, nome, area_ha, tipo_colheita,
         prod_esp, prod_col, safra) = linha
        # Monta um dicionário equivalente ao que criar_talhao() produziria.
        talhao = {
            "id_local": None,                    # Ainda não temos id_local (veio do BD).
            "id_oracle": int(id_db),             # ID real no Oracle.
            "nome": nome,
            "area_ha": float(area_ha),
            "tipo_colheita": tipo_colheita,
            "producao_esperada_t": float(prod_esp),
            "producao_colhida_t": float(prod_col),
            "safra": safra,
            # Campos derivados serão preenchidos por recalcular_talhao.
            "perda_t": 0.0,
            "perda_pct": 0.0,
            "classificacao": "",
        }
        # Recalcula perdas/classe com base no que veio do banco.
        recalcular_talhao(talhao)
        # Adiciona ao resultado final.
        resultado.append(talhao)
    # Fecha o cursor.
    cursor.close()
    # Devolve a lista montada.
    return resultado


# ---------------------------------------------------------------------------
# ATUALIZAR
# ---------------------------------------------------------------------------
def atualizar_talhao(conn, id_oracle, campos):
    """Atualiza campos de um talhão existente no Oracle.

    'campos' é um dicionário com os campos atualizáveis. Só são aceitos os
    campos brancos (editáveis); campos derivados (perda_*) nunca vão ao banco.
    """
    cursor = conn.cursor()
    # UPDATE com todos os campos editáveis + WHERE por id.
    sql = """
        UPDATE talhoes
           SET nome = :nome,
               area_ha = :area_ha,
               tipo_colheita = :tipo_colheita,
               producao_esperada_t = :producao_esperada_t,
               producao_colhida_t = :producao_colhida_t,
               safra = :safra
         WHERE id = :id_oracle
    """
    # Monta o bind dict unindo os campos novos com o id.
    binds = {
        "nome": campos["nome"],
        "area_ha": campos["area_ha"],
        "tipo_colheita": campos["tipo_colheita"],
        "producao_esperada_t": campos["producao_esperada_t"],
        "producao_colhida_t": campos["producao_colhida_t"],
        "safra": campos["safra"],
        "id_oracle": id_oracle,
    }
    # Executa e persiste.
    cursor.execute(sql, binds)
    # rowcount informa quantas linhas foram afetadas (deve ser 1).
    afetadas = cursor.rowcount
    conn.commit()
    cursor.close()
    return afetadas


# ---------------------------------------------------------------------------
# EXCLUIR
# ---------------------------------------------------------------------------
def excluir_talhao(conn, id_oracle):
    """Remove um talhão do Oracle pelo id."""
    cursor = conn.cursor()
    # DELETE simples com bind para evitar SQL injection.
    cursor.execute("DELETE FROM talhoes WHERE id = :id_oracle",
                   {"id_oracle": id_oracle})
    # Guarda quantas linhas foram removidas.
    afetadas = cursor.rowcount
    # Persiste a exclusão.
    conn.commit()
    cursor.close()
    return afetadas


# ---------------------------------------------------------------------------
# SINCRONIZAÇÃO BIDIRECIONAL (diferencial do projeto)
# ---------------------------------------------------------------------------
def sincronizar_local_para_oracle(conn, talhoes_memoria):
    """Envia para o Oracle todos os talhões em memória que ainda não foram sincronizados.

    Modifica a lista in-place preenchendo o campo 'id_oracle' dos talhões enviados.
    Retorna a quantidade de talhões enviados.
    """
    # Contador de registros enviados nesta sincronização.
    enviados = 0
    # Percorre cada talhão da memória.
    for talhao in talhoes_memoria:
        # Se já tem id_oracle preenchido, já foi enviado antes; pula.
        if talhao.get("id_oracle") is not None:
            continue
        # Insere no banco e recebe o id gerado.
        novo_id = inserir_talhao(conn, talhao)
        # Guarda o id_oracle de volta no dict em memória.
        talhao["id_oracle"] = novo_id
        # Incrementa contador.
        enviados += 1
    # Retorna para o chamador apresentar a mensagem.
    return enviados


def sincronizar_oracle_para_local(conn):
    """Puxa todos os talhões do Oracle e devolve como nova lista em memória.

    Atribui ids locais sequenciais preservando a ordem do banco.
    """
    # Lê tudo que está no Oracle.
    talhoes = listar_talhoes(conn)
    # Atribui id_local sequencial (1..N) — conveniência para exibição.
    for i, talhao in enumerate(talhoes, start=1):
        talhao["id_local"] = i
    # Devolve a lista — o chamador substitui o estado em memória por ela.
    return talhoes
